name: enpheeph
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - cudatoolkit=10.1.*
  - cudatoolkit-dev=10.1.*
  - cupy>=9.*
  - openblas-devel
  - gcc_linux-64
  - gxx_linux-64
  - python=3.9.*
  - pip=21
  - pip:
    - norse
    - pytorch-lightning
    - pytorch-lightning-bolts
    - tonic
    - torchsummary
    # for Windows change linux_x86_64 to win_amd64
    # for other torch versions/configurations, check out
    # https://download.pytorch.org/whl/torch_stable.html
    - https://download.pytorch.org/whl/cu101/torch-1.8.1%2Bcu101-cp39-cp39-linux_x86_64.whl
    - https://download.pytorch.org/whl/cu101/torchvision-0.9.1%2Bcu101-cp39-cp39-linux_x86_64.whl
