# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


default_language_version:
  python: python3.10


minimum_pre_commit_version: 3.1.1


repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
      args: [
          '--maxkb=350',
          # this is ok, but since in papers we have some large files, we just considered
          # the staged one
          # '--enforce-all',
      ]
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: check-xml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    # to add -*- coding: utf-8 -*- to the top of python files
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [
        "--autofix",
        "--indent",
        "4",
      ]
    - id: name-tests-test
      args: ['--django']  # we match for test*.py
    # to sort entries in requirements.txt
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore
    - id: python-check-mock-methods
    # matches also eval in PyTorch
    # - id: python-no-eval
    - id: python-no-log-warn
    # not needed as we use Python 3.8+
    - id: python-use-type-annotations
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    - id: forbid-crlf
    - id: remove-crlf
    - id: forbid-tabs
    - id: remove-tabs
      args:
        - --whitespaces-count
        - "4"  # defaults to: 4
    - id: insert-license
      files: \.py$
      args:
        - --license-filepath
        # defaults to: LICENSE.txt
        - COPYRIGHT
        - --comment-style
        # defaults to: #
        - "#"
        - --use-current-year

  - repo: local
    hooks:
      # - id: nox-test
      #   name: test session with nox
      #   entry: nox --noxfile .noxfile.py --envdir .nox.pre-commit --session test --verbose --add-timestamp
      #   pass_filenames: false
      #   stages: [manual]
      #   language: python
      #   additional_dependencies: ['nox==2022.11.21']
      # - id: nox-linting
      #   name: linting session with nox
      #   entry: nox --noxfile .noxfile.py --envdir .nox.pre-commit --session linting --verbose --add-timestamp --
      #   types_or: [python, pyi, jupyter]
      #   pass_filenames: true
      #   stages: [manual]
      #   language: python
      #   additional_dependencies: ['nox==2022.11.21']
      - id: mkinit-init-generation
        name: generate init automatically with mkinit
        entry: mkinit --recursive --black --lazy src/enpheeph
        types_or: [python]
        pass_filenames: false
        # if not set it covers all stages
        # stages: [pre-commit, manual]
        language: python
        additional_dependencies: ['mkinit==1.0.0']

  # ruff before other linting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.245'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      # args: [--ignore-missing-imports, src/enpheeph]
      # args: [--ignore-missing-imports, --config-file=pyproject.toml, src/enpheeph]
      pass_filenames: true

# continuous integration configuration for pre-commit.ci
# freely available to open-source repositories
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  submodules: false
