# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.9
default_stages: [commit]
minimum_pre_commit_version: 2.15.0
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    # to add -*- coding: utf-8 -*- to the top of python files
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    # not needed, it is only for the ending, not for the start
    # - id: name-tests-test
    # to sort entries in requirements.txt
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    # with stable it always uses the latest version
    # otherwise use a specific tag
    rev: stable
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        # the additional dependencies are installed if required in the
        # execution
        # additional_dependencies: [
        #     cupy>=9.4.0,
        #     numpy,
        #     pytorch-lightning>=1.4.5,
        #     sqlalchemy>=1.4.22,
        #     torch>=1.9,
        # ]
        args: [
            # --no-strict-optional,
            # mypy is used from a venv, so it will not have all the
            # dependencies available
            --ignore-missing-imports
        ]
