# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


default_language_version:
  python: python3.10


default_stages: [commit, merge-commit, manual]


minimum_pre_commit_version: 3.1.1


repos:

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.0.1
  #   hooks:
  #   - id: check-added-large-files
  #     args: [
  #         '--maxkb=350',
  #         '--enforce-all',
  #     ]
  #   - id: check-ast
  #   - id: check-builtin-literals
  #   - id: check-byte-order-marker
  #   - id: check-case-conflict
  #   - id: check-docstring-first
  #   - id: check-executables-have-shebangs
  #   - id: check-merge-conflict
  #   - id: check-symlinks
  #   - id: check-json
  #   - id: check-toml
  #   - id: check-vcs-permalinks
  #   - id: check-yaml
  #   - id: check-xml
  #   - id: debug-statements
  #   - id: destroyed-symlinks
  #   - id: detect-private-key
  #   - id: end-of-file-fixer
  #   - id: fix-byte-order-marker
  #   # to add -*- coding: utf-8 -*- to the top of python files
  #   - id: fix-encoding-pragma
  #   - id: mixed-line-ending
  #   - id: pretty-format-json
  #     args: [
  #       "--autofix",
  #       "--indent",
  #       "4",
  #     ]
  #   - id: name-tests-test
  #     args: ['--django']  # we match for test*.py
  #   # to sort entries in requirements.txt
  #   - id: requirements-txt-fixer
  #   - id: sort-simple-yaml
  #   - id: trailing-whitespace


  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.9.0
  #   hooks:
  #   - id: python-check-blanket-noqa
  #   - id: python-check-blanket-type-ignore
  #   - id: python-check-mock-methods
  #   - id: python-no-eval
  #   - id: python-no-log-warn
  #   # not needed as we use Python 3.8+
  #   - id: python-use-type-annotations
  #   - id: rst-backticks
  #   - id: rst-directive-colons
  #   - id: rst-inline-touching-normal
  #   - id: text-unicode-replacement-char

  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.1.11
  #   hooks:
  #   - id: forbid-crlf
  #   - id: remove-crlf
  #   - id: forbid-tabs
  #   - id: remove-tabs
  #     args:
  #       - --whitespaces-count
  #       - "4"  # defaults to: 4
  #   - id: insert-license
  #     files: .py
  #     args:
  #       - --license-filepath
  #       # defaults to: LICENSE.txt
  #       - COPYRIGHT
  #       - --comment-style
  #       # defaults to: #
  #       - "#"

  #   - repo: https://github.com/psf/black
  #   # with stable it always uses the latest version
  #   # otherwise use a specific tag
  #   # pre-commit gives warnings for mutable references, as they are not updated
  #   # unless you uses pre-commit autoupdate
  #   rev: 21.9b0
  #   hooks:
  #   - id: black
  #     args: [
  #         "--line-length=88",
  #         "--target-version=py38",
  #     ]

  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v1.17.0
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #   - id: flake8
  #     args: [
  #         "--max-line-length=88",
  #         "--extend-ignore=E203",
  #         "--max-complexity=10",
  #     ]

  # # mypy and pre-commit hooks are not nice together if the project
  # # has dependencies which are difficult to install
  # # for now we simply run it locally and later also in a CI
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910-1  # Use the sha / tag you want to point at
  #   hooks:
  #   # there are issues in using the project-wide configuration, so
  #   # things should be repeated here if needed, e.g. skipping tests
  #   - id: mypy
  #     # the additional dependencies are installed if required in the
  #     # execution
  #     additional_dependencies: [
  #     #     cupy>=9.4.0,
  #     #     numpy,
  #     #     pytorch-lightning>=1.4.5,
  #     #     sqlalchemy>=1.4.22,
  #     #     torch>=1.9,
  #       "packaging==21.0",
  #       "sqlalchemy[mypy]==1.4.22",
  #       "types-setuptools==57.4.2",
  #       "types-pkg-resources==0.1.3",
  #     ]
  #     args: [
  #       # mypy is used from a venv, so it will not have all the
  #       # dependencies available
  #       --ignore-missing-imports,
  #     ]
  #     files: ^src/enpheeph, ^tests,

  - repo: local
    hooks:
      - id: nox-test
        name: test session with nox
        entry: nox --noxfile .noxfile.py --session test --verbose --add-timestamp
        pass_filenames: false
        stages: [manual]
        language: python
        additional_dependencies: ['nox==2022.11.21']

# continuous integration configuration for pre-commit.ci
# freely available to open-source repositories
# it will not be run until we are open-source
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  # skip: [mypy]
  submodules: false
