channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cupy=9.0.0
  - fastrlock=0.6
  - ffmpeg=4.2.2
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=2.10
  - intel-openmp=2021.2.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libidn2=2.3.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - nettle=3.7.2
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.1.1
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.10
  - python_abi=3.8
  - pytorch=1.8.1
  - readline=8.1
  - requests=2.25.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchtext=0.9.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wheel=0.36.2
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==21.2.0
    - cachetools==4.2.2
    - docstring-parser==0.8.1
    - fsspec==2021.5.0
    - future==0.18.2
    - google-auth==1.30.1
    - grpcio==1.38.0
    - jsonargparse==3.12.1
    - markdown==3.3.4
    - multidict==5.1.0
    - packaging==20.9
    - protobuf==3.17.1
    - pydeprecate==0.3.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytorch-lightning==1.3.3
    - pytorch-lightning-bolts==0.3.2
    - pyyaml==5.4.1
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.3.2
    - torchsummary==1.5.1
    - werkzeug==2.0.1
    - yarl==1.6.3
