model:
  class_path: src.dnn.pl.utils.mixins.vision.plvisionwrapper.PLVisionWrapper
  init_args:
    model:
      class_path: torchvision.models.AlexNet
      init_args: {}
    optimizer_class: adam
    lr: 1e-3
    normalize_prob_func:
      class_path: torch.nn.Softmax
      init_args:
        dim: -1
    loss_func:
      class_path: torch.nn.CrossEntropyLoss
      init_args: {}
    accuracy_func:
      class_path: torchmetrics.Accuracy
      init_args: {}

data:
  class_path: pl_bolts.datamodules.ImagenetDataModule
  init_args:
    data_dir: /shared/ml/datasets/ImageNet_2012/
    shuffle: true
    pin_memory: true
