model:
  class_path: src.dnn.pl.utils.mixins.vision.plvisionwrapper.PLVisionWrapper
  init_args:
    model:
      class_path: torchvision.models.AlexNet
    optimizer_class:
      class_path: torch.optim.Adam
    lr: 1e-3
    normalize_prob_func:
      class_path: torch.nn.Softmax
      init_args:
        dim: -1
    loss_func:
      class_path: torch.nn.CrossEntropyLoss
    accuracy_func:
      class_path: torchmetrics.Accuracy

data:
  class_path: pl_bolts.datamodules.ImagenetDataModule
  init_args:
    data_dir: /shared/ml/datasets/ImageNet_2012/
    shuffle: true
    pin_memory: true
