# setting this seed forces all the PRNGs to have the same seed, improving
# reproducibility
seed_everything: 42

# this configuration goes into the dataloaders, but this is extra configuration
# which is defined due to the case class for datamodules being a
# LightningDataModule
# hence, we don't include this bit of configuration in our custom configuration
# but we leave it commented here as reference
# data:
#   train_transforms: null
#   val_transforms: null
#   test_transforms: null
#   dims: null

# we can refer to another YAML file
trainer: custom_trainer_config.yml
