# we test the repository every time there is a new push on main
name: tests

# events that trigger the workflow
on:
  # we select push for the selected branches
  push:
    branches:
      - main
  # as well as when there are any pull requests
  pull_request:
    branches:
      - main

jobs:
  # name of the job
  pytest:

    # the system to run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # for now a small grid is more than enough
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        python-version:
          - 3.8
          - 3.9

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 40

    steps:
    # we check out the repository
    - name: Repository check-out
      uses: actions/checkout@v2

    # we set up the Python environment
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Github Actions: Run step on specific OS: https://stackoverflow.com/a/57948488/4521646

    - name: Install test dependencies
      run: |
        python --version
        pip --version
        pip install --requirement requirements.txt --requirement requirements/test/base.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        pip list
      shell: bash

    - name: Run pytest
      run: |
        python -m pytest -n auto -vvv --durations=0 --full-trace --junitxml=junit/test-results-${{ runner.os }}-py${{ matrix.python-version }}.xml

    # this is required for sharing data with other jobs, as each job has a
    # different runner
    - name: Upload pytest results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ runner.os }}-${{ matrix.python-version }}
        path: junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml
      if: failure()
