### DEFAULT CUSTOM CONFIG ###
seed_everything: 42

trainer: custom_trainer_config.yml

### END OF DEFAULT CUSTOM CONFIG ###

model:
  model:
    class_path: src.ml.models.vision.lenet5.LeNet5
    init_args: {}
  init_before_fit: true
  # for float with exp use .0 instead of integer
  learning_rate: 1.0e-3
  batch_size: 1
  example_input_array_size: null
  optimizer_classes:
    - class_path: torch.optim.Adam
      init_args: {}
  lr_scheduler_classes: [[]]
  lr_scheduler_configs: [[]]
  normalize_prob_func:
    class_path: torch.nn.Softmax
    init_args:
      dim: -1
  loss_func:
    class_path: torch.nn.CrossEntropyLoss
    init_args: {}
  pre_accuracy_func:
    class_path: torch.nn.Identity
    init_args: {}
  accuracy_func:
    class_path: torchmetrics.Accuracy
    init_args: {}

data:
  class_path: pl_bolts.datamodules.MNISTDataModule
  init_args:
    data_dir: datasets/MNIST/
    shuffle: true
    pin_memory: true
    batch_size: 1
